[build]
  command = "npm run build"
  publish = "dist"

# Ambiente deve ser um MAPA (tabela), não um array
[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
