[build]
  command = "npm run build"
  publish = "dist"
  environment = ["NODE_VERSION"]

[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
